blockchain_lab/blockchain_lab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', include('mainApp.urls')),
    path('', RedirectView.as_view(url='mainApp/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static('/uploads/', document_root=os.path.join(settings.BASE_DIR, 'uploads'))

blockchain_lab/catalog/urls.py
from django.urls import path, include
from . import views
from django.views.generic import ListView, DetailView
from catalog.models import Procurement

urlpatterns = [
    path('', ListView.as_view(queryset=Procurement.objects.all(),
    template_name="catalog/homePage.html")),
]

blockchain_lab/mainApp/urls.py
from django.urls import path, include
from . import views
from django.views.generic import ListView, DetailView
from mainApp.models import SERVICES, About, Portfolio, Team
from .views import IndexView


urlpatterns = [
    path('', 
    IndexView.as_view(),
    name="home_list"
        ),
]

blockchain_lab/catalog/models.py
from django.db import models

class ProcurementFiles(models.Model):
    file = models.FileField(upload_to='uploads/')

class Procurement(models.Model):
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    title = models.CharField(max_length=500)
    description = models.TextField()
    files = models.ManyToManyField(ProcurementFiles)
    
    def __str__(self):
        return self.title
'''class TableFeedFile(models.Model):
    #feed = models.ForeignKey(Feed, on_delete=models.CASCADE)
    files = models.ManyToManyField(TableFeed)
    #file = models.FileField(upload_to='uploads/')
    #files2 = models.FileField(upload_to='uploads/', null=True, blank=True)
    
class TableFeed(models.Model):
    #user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='feeds')
    start_date = models.DateTimeField(null=True)
    end_date = models.DateTimeField(null=True)
    title = models.CharField(max_length=500)
    description = models.TextField()
    #files = models.ManyToManyField(TableFeedFile)
    file = models.FileField(upload_to='uploads/')

    '''

'''TableForm = modelform_factory(Table)'''

'''class ProcurementFiles(models.Model):
    procurement_id = int
    procurement_files = models.FileField()'''

'''class Feed(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, related_name='feeds')
    text=models.TextField(blank=False, max_length=500)
    files=models.ManyToManyField(FeedFile)

class FeedFile(models.Model):
    file = models.FileField(upload_to='uploads/')'''

blockchain_lab/mainApp/models.py
from django.db import models

class SERVICES(models.Model):
    s_title = models.CharField(max_length=200)
    s_post = models.TextField()
    #s_image = models.ImageField(null=True, upload_to='images/')

    def __str__(self):
        return self.s_title

class About(models.Model):
    a_title = models.CharField(max_length=200)
    a_post = models.TextField()
    a_image = models.ImageField(null=True, upload_to='images/')

    def __str__(self):
        return self.a_title

class Portfolio(models.Model):
    p_title = models.CharField(max_length=200)
    p_post = models.TextField()
    p_image = models.ImageField(null=True, upload_to='images/')

    def __str__(self):
        return self.p_title

class Team(models.Model):
    t_title = models.CharField(max_length=200)
    t_post = models.TextField()
    t_image = models.ImageField(null=True, upload_to='images/')

    def __str__(self):
        return self.t_title

blockchain_lab/catalog/forms.py
from django import forms
from catalog.models import Procurement
from django.forms.widgets import ClearableFileInput

class ProcurementForm(forms.ModelForm):
    class Meta:
        model = Procurement
        fields = ('description', 'files', 'title')
        widgets = {
            'files': ClearableFileInput(attrs={'multiple': True}),
        }
        # widget is important to upload multiple files

blockchain_lab/blockchain_data/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return HttpResponse("<h3>Это главная страница!</h3>")

blockchain_lab/catalog/views.py
from django.shortcuts import render
from .forms import ProcurementForm
from django.shortcuts import redirect
from .models import Procurement

# in your template.html <form> tag must include enctype="multipart/form-data"

'''def index(request):
    return render(request, 'catalog/homePage.html')'''

def model_form_upload(request):
    if request.method == 'POST':
        form = ProcurementForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = ProcurementForm()
    return render(request, 'catalog/homePage.html', {
        'form': form
    })

blockchain_lab/mainApp/views.py
from django.shortcuts import render
from django.views import generic
from .models import SERVICES, About, Portfolio, Team

class IndexView(generic.ListView):
    context_object_name = 'home_list'
    template_name = 'mainApp/posts.html'
    queryset = Portfolio.objects.all()

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['about_list'] = About.objects.all()
        context['team_list'] = Team.objects.all()
        context['services_list'] = SERVICES.objects.all()
        return context

blockchain_lab/catalog/templates/catalog/homePage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Agency - Start Bootstrap Theme</title>
    <link rel="icon" type="image/x-icon" href="/static/assets/img/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/static/css/styles.css" rel="stylesheet" />
</head>

<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top"><img src="/static/assets/img/navbar-logo.svg" alt="" /></a><button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">Menu<i class="fas fa-bars ml-1"></i></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav text-uppercase ml-auto">
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="http://127.0.0.1:8000">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Masthead-->
    <header class="masthead">
        <div class="container">
            <div class="masthead-subheading">Welcome To Catalog!</div>
            <div class="masthead-heading text-uppercase">It's Nice To Meet You</div>
            <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger" href="#services">Tell Me More</a>
        </div>
    </header>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Start date</th>
                    <th>End date</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th colspan="2">Files</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for procurement in procurement_list %} {% if forloop.counter|divisibleby:2 %}
                <tr class="active">
                    {% else %}
                    <tr class="success">
                        {% endif %}
                        <td>{{procurement.start_date|date:"d-m-y"}}</td>
                        <td>{{procurement.end_date|date:"d-m-y"}}</td>
                        <td>{{procurement.title}}</td>
                        <td>{{procurement.description}}</td>
                        <td colspan="2"><a href="{{procurement.files.url}}">Files</a></td>
                    </tr>
                    {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- Footer-->
    <footer class="footer py-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 text-lg-left">Copyright © Your Website 2020</div>
                <div class="col-lg-4 my-3 my-lg-0">
                    <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a><a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a><a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                </div>
                <div class="col-lg-4 text-lg-right"><a class="mr-3" href="#!">Privacy Policy</a><a href="#!">Terms of Use</a></div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <!-- Contact form JS-->
    <script src="/static/assets/mail/jqBootstrapValidation.js"></script>
    <script src="/static/assets/mail/contact_me.js"></script>
    <!-- Core theme JS-->
    <script src="/static/js/scripts.js"></script>
</body>

</html>

blockchain_lab/mainApp/templates/mainApp/blockchain.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>ЦЕНТР‌ ‌ТЕХНОЛОГИЧЕСКОГО‌ ‌РАЗВИТИЯ‌ ИНТЕЛЛЕКТУАЛЬНЫХ‌ ‌СИСТЕМ</title>
    <link rel="icon" type="image/x-icon" href="static/assets/img/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="static/assets/fonts/Monserrat" rel="stylesheet" type="text/css" />
    <link href="static/assets/fonts/Rubik" rel="stylesheet" type="text/css" />
    <link href="static/assets/fonts/Lato" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="static/css/style_ctris.css" rel="stylesheet" />
</head>

<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top"><img src="static/assets/imgages/logo.png" alt="" /></a><button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">Menu<i class="fas fa-bars ml-1"></i></button>
        </div>
        <div class="header">
            <header>ТОО "ЦЕНТР‌ ‌ТЕХНОЛОГИЧЕСКОГО‌ ‌РАЗВИТИЯ‌ ИНТЕЛЛЕКТУАЛЬНЫХ‌ ‌СИСТЕМ"</header>
        </div>
    </nav>
    <hr>
    <h1>ОСНОВНЫЕ НАПРАВЛЕНИЯ ДЕЯТЕЛЬНОСТИ</h1>
    <div class="block">
        <img class="img-fluid" src="static/assets/images/01.png" alt="" />
        <div class="portfolio-caption-heading">Исследование и консалтинг</div>
        <div class="portfolio-caption-subheading text-muted">Исследовательская деятельность сфокусирована на проектах, имеющих прикладной характер следующих областей:</div>
        <hr>
        <ul>
            <li>Бизнес-аналитика</li>
            <hr>
            <li>Финансовые технологии</li>
            <hr>
            <li>Реинжиниринг и цифровизация бизнес-процессов с применением следующих технологий, среди прочих:
                <ol>
                    <li>Blockchain</li>
                    <li>Искусственный интеллект</li>
                    <li>Большие данные</li>
                    <li>Облачные технологии</li>
                </ol>
            </li>
        </ul>
    </div>





    <footer class="footer py-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 text-lg-left">Blockchain & Big data Lab, 2020 год</div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <!-- Core theme JS-->
    <script src="static/js/scripts.js"></script>
</body>

</html>

blockchain_lab/mainApp/templates/mainApp/posts.html
{% extends "mainApp/index.html" %} {% block content %}

<!-- Services-->
<section class="page-section" id="services">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Services</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <div class="row text-center">
            {% for services in services_list %}
            <div class="col-md-4">
                {% if forloop.counter|divisibleby:2 %}
                <span class="fa-stack fa-4x"><i class="fas fa-circle fa-stack-2x text-primary"></i><i class="fas fa-shopping-cart fa-stack-1x fa-inverse"></i></span> {% else %}<span class="fa-stack fa-4x"><i class="fas fa-circle fa-stack-2x text-primary"></i><i class="fas fa-laptop fa-stack-1x fa-inverse"></i></span>                {% if forloop.counter and forloop.last %}<span class="fa-stack fa-4x"><i class="fas fa-circle fa-stack-2x text-primary"></i><i class="fas fa-lock fa-stack-1x fa-inverse"></i></span> {% endif %} {% endif %}
                <h4 class="my-3">{{services.s_title}}</h4>
                <p class="text-muted">{{services.s_post}}</p>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- Portfolio Grid-->
<section class="page-section bg-light" id="portfolio">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Portfolio</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <div class="row">
            {% for portfolios in home_list %}
            <div class="col-lg-4 col-sm-6 mb-4">
                <div class="portfolio-item">
                    <a class="portfolio-link" data-toggle="modal" href="#portfolioModal2">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                        </div>
                        <img class="img-fluid" src="{{portfolios.p_image.url}}" alt="" /></a>
                    <div class="portfolio-caption">
                        <div class="portfolio-caption-heading">{{portfolios.p_title}}</div>
                        <div class="portfolio-caption-subheading text-muted">{{portfolios.p_post|safe|linebreaks}}</div>
                    </div>
                </div>
            </div>
            {% endfor%}
        </div>
    </div>
</section>
<!-- About-->
<section class="page-section" id="about">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">About</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <ul class="timeline">
            {% for about in about_list %} {% if forloop.counter|divisibleby:2 %}
            <li class="timeline-inverted">{% else %}
                <li>{% endif %}
                    <div class="timeline-image"><img class="rounded-circle img-fluid" src="{{about.a_image.url}}" alt="" /></div>
                    <div class="timeline-panel">
                        <div class="timeline-heading">
                            <h4>2009-2011</h4>
                            <h4 class="subheading">{{about.a_title}}</h4>
                        </div>
                        <div class="timeline-body">
                            <p class="text-muted">{{about.a_post}}</p>
                        </div>
                    </div>
                </li>
                {% endfor %}
                <li class="timeline-inverted">
                    <div class="timeline-image">
                        <h4>Be Part<br />Of Our<br />Story!</h4>
                    </div>
                </li>
        </ul>
    </div>
</section>
<!-- Team-->
<section class="page-section bg-light" id="team">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Our Amazing Team</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <div class="row">
            {% for team in team_list %}
            <div class="col-lg-4">
                <div class="team-member">
                    <img class="mx-auto rounded-circle" src="{{team.t_image.url}}" alt="" />
                    <h4>{{team.t_post}}</h4>
                    <p class="text-muted">{{team.t_title}}</p>
                    <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a><a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a><a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col-lg-8 mx-auto text-center">
                <p class="large text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}